In [ ]:
#### Popular ways to Filter data in your dataframe ###
# Sriram Parthasarathy
# LICENSES : MIT

'''
Filtering extracts specific subsets of data based on defined conditions (e.g., values, ranges, or patterns).
When to use: Use to focus on relevant data, remove noise, or meet analysis criteria (e.g., time periods, customer segments).
Examples:

 - Extracting sales data for Q1 2024 to analyze seasonal trends.

- Isolating high-value customers (e.g., revenue > $10K) for targeted campaigns.

- Removing incomplete records to ensure data quality before modeling.

Additional Reading:
Please refer to my articles on Medium for more details:

Practical Strategies to Handle Missing Values
https://medium.com/data-science/practical-strategies-to-handle-missing-values-626f9c43870b?source=your_stories_page--------------------------------------------

The Shopping Cart Abandonment Problem: How Machine Learning Can Help!
https://medium.com/managing-digital-products/the-shopping-cart-abandonment-problem-how-machine-learning-can-help-eb690f1dc4f6?source=your_stories_page--------------------------------------------

How to Measure & Optimise Your Predictive Model for Prime Time?
https://medium.com/managing-digital-products/how-to-measure-optimise-your-predictive-model-for-prime-time-3b9f6072f85c?source=your_stories_page--------------------------------------------

Increasing The Accuracy of Predictive Models with Stacked Ensemble Techniques: Healthcare Example
https://medium.com/managing-digital-products/increasing-the-accuracy-of-predictive-model-with-stacked-ensemble-techniques-a-healthcare-example-135d36b9a2b7?source=your_stories_page--------------------------------------------

AI Powered Automatic Classification: The Challenges in Managing Data in Clinical Trials
https://medium.com/managing-digital-products/ai-powered-automatic-classification-the-challenges-in-managing-data-in-clinical-trials-6639e7aa1a7d?source=your_stories_page--------------------------------------------

How Do You Measure If Your Customer Churn Predictive Model Is Good?
https://medium.com/data-science/how-do-you-measure-if-your-customer-churn-predictive-model-is-good-187a49a9eee3?source=your_stories_page--------------------------------------------


Practical Data Augmentation Techniques for Predictive Models
https://medium.com/hackernoon/practical-data-augmentation-techniques-for-predictive-models-b51599253c30?source=your_stories_page--------------------------------------------

Machine Learning for Product Managers: Defining the business problem
https://medium.com/managing-digital-products/machine-learning-for-product-managers-defining-the-business-problem-f0e968d09ee7?source=your_stories_page--------------------------------------------

'''

import pandas as pd

# ----------------------------
# STEP 1: Create sample DataFrame
# ----------------------------
# To illustrate I am using sample dataset as I can't share a real customer dataset
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'age': [25, 35, 45, 28, 32, 45],
    'education': ['Bachelors', 'Masters', 'PhD', 'Bachelors', 'Masters', 'PhD'],
    'salary': [50000, 60000, 80000, 52000, 58000, 82000]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# ----------------------------
# STEP 2: Filtering
# ----------------------------

# 1. Filter rows where age > 30
filtered_age = df[df['age'] > 30]
print("\nAge > 30:\n", filtered_age)

# 2. Filter rows where education is 'Masters'
filtered_edu = df[df['education'] == 'Masters']
print("\nEducation == 'Masters':\n", filtered_edu)

# 3. Filter rows where age is between 30 and 40
filtered_range = df[(df['age'] >= 30) & (df['age'] <= 40)]
print("\nAge between 30 and 40:\n", filtered_range)

# 4. Filter rows where name is in a list
filtered_names = df[df['name'].isin(['Alice', 'Eva'])]
print("\nName in ['Alice', 'Eva']:\n", filtered_names)

# 5. Filter rows where education is not 'PhD'
not_phd = df[df['education'] != 'PhD']
print("\nEducation != 'PhD':\n", not_phd)

# 6. Multiple conditions (AND): Age > 30 and education is 'Masters'
filtered_and = df[(df['age'] > 30) & (df['education'] == 'Masters')]
print("\nAge > 30 AND Education == 'Masters':\n", filtered_and)

# 7. Multiple conditions (OR): Age < 30 or education is 'PhD'
filtered_or = df[(df['age'] < 30) | (df['education'] == 'PhD')]
print("\nAge < 30 OR Education == 'PhD':\n", filtered_or)

# ----------------------------
# STEP 3: Grouping and Aggregation
# ----------------------------

# 1. Group by education and get average salary
grouped_avg_salary = df.groupby('education')['salary'].mean().reset_index()
print("\nAverage Salary by Education:\n", grouped_avg_salary)

# 2. Group by age and count number of people
grouped_age_count = df.groupby('age')['name'].count().reset_index(name='count')
print("\nCount of People by Age:\n", grouped_age_count)

# 3. Group by education and get both mean and max salary
grouped_multi = df.groupby('education')['salary'].agg(['mean', 'max']).reset_index()
print("\nMean and Max Salary by Education:\n", grouped_multi)

# 4. Average salary by age groups
# First create age groups
bins = [0, 30, 40, 100]
labels = ['<30', '30 to 40', '>40']
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)

# Then calculate average salary by age group
avg_salary_by_age = df.groupby('age_group')['salary'].mean().reset_index()
print("Average salary by age group:")
print(avg_salary_by_age)

Original DataFrame:
       name  age  education  salary
0    Alice   25  Bachelors   50000
1      Bob   35    Masters   60000
2  Charlie   45        PhD   80000
3    David   28  Bachelors   52000
4      Eva   32    Masters   58000
5    Frank   45        PhD   82000

Age > 30:
       name  age education  salary
1      Bob   35   Masters   60000
2  Charlie   45       PhD   80000
4      Eva   32   Masters   58000
5    Frank   45       PhD   82000

Education == 'Masters':
   name  age education  salary
1  Bob   35   Masters   60000
4  Eva   32   Masters   58000

Age between 30 and 40:
   name  age education  salary
1  Bob   35   Masters   60000
4  Eva   32   Masters   58000

Name in ['Alice', 'Eva']:
     name  age  education  salary
0  Alice   25  Bachelors   50000
4    Eva   32    Masters   58000

Education != 'PhD':
     name  age  education  salary
0  Alice   25  Bachelors   50000
1    Bob   35    Masters   60000
3  David   28  Bachelors   52000
4    Eva   32    Masters   58000

Age > 30 AND Education == 'Masters':
   name  age education  salary
1  Bob   35   Masters   60000
4  Eva   32   Masters   58000

Age < 30 OR Education == 'PhD':
       name  age  education  salary
0    Alice   25  Bachelors   50000
2  Charlie   45        PhD   80000
3    David   28  Bachelors   52000
5    Frank   45        PhD   82000

Average Salary by Education:
    education   salary
0  Bachelors  51000.0
1    Masters  59000.0
2        PhD  81000.0

Count of People by Age:
    age  count
0   25      1
1   28      1
2   32      1
3   35      1
4   45      2

Mean and Max Salary by Education:
    education     mean    max
0  Bachelors  51000.0  52000
1    Masters  59000.0  60000
2        PhD  81000.0  82000
Average salary by age group:
  age_group   salary
0       <30  51000.0
1  30 to 40  59000.0
2       >40  81000.0

<ipython-input-1-eefe2aaa9140>:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_salary_by_age = df.groupby('age_group')['salary'].mean().reset_index()